image: node:lts
variables:
  NO_PROXY: docker,localhost,127.0.0.1,172.0.0.0/8,*.mtt,*.local,github.com
  no_proxy: "$NO_PROXY"
  HTTP_PROXY: http://proxy.porta.local:3128
  http_proxy: "$HTTP_PROXY"
  HTTPS_PROXY: http://proxy.porta.local:3128
  https_proxy: "$HTTPS_PROXY"

workflow:
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"

before_script:
  - git config --global http.sslverify false
  - npm i

release:
  only:
    - master
  resource_group: release
  script:
    - npm run build-lib
    - npm run build-doc
    - npm config set access public
    - npx semantic-release
  stage: release

stages:
  - release
