name: Remote SSH Command

on:
  push:
  pull_request:
  schedule:
    - cron: "*/30 * * * *"

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: 217.144.187.254
        username: root
        password: 6X9rEYln8spq
        port: 22
        script: bash run_commands.sh
        debug: true
        timeout: 200s
        command_timeout: 30m
